# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lyn/Documents/GitHub/Vulkraft

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lyn/Documents/GitHub/Vulkraft

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lyn/Documents/GitHub/Vulkraft/CMakeFiles /home/lyn/Documents/GitHub/Vulkraft//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lyn/Documents/GitHub/Vulkraft/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Vulkraft

# Build rule for target.
Vulkraft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vulkraft
.PHONY : Vulkraft

# fast build rule for target.
Vulkraft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/build
.PHONY : Vulkraft/fast

#=============================================================================
# Target rules for targets named Shaders

# Build rule for target.
Shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Shaders
.PHONY : Shaders

# fast build rule for target.
Shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shaders.dir/build.make CMakeFiles/Shaders.dir/build
.PHONY : Shaders/fast

src/app.o: src/app.cpp.o
.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/descriptors.o: src/descriptors.cpp.o
.PHONY : src/descriptors.o

# target to build an object file
src/descriptors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/descriptors.cpp.o
.PHONY : src/descriptors.cpp.o

src/descriptors.i: src/descriptors.cpp.i
.PHONY : src/descriptors.i

# target to preprocess a source file
src/descriptors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/descriptors.cpp.i
.PHONY : src/descriptors.cpp.i

src/descriptors.s: src/descriptors.cpp.s
.PHONY : src/descriptors.s

# target to generate assembly for a file
src/descriptors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/descriptors.cpp.s
.PHONY : src/descriptors.cpp.s

src/engineDevice.o: src/engineDevice.cpp.o
.PHONY : src/engineDevice.o

# target to build an object file
src/engineDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/engineDevice.cpp.o
.PHONY : src/engineDevice.cpp.o

src/engineDevice.i: src/engineDevice.cpp.i
.PHONY : src/engineDevice.i

# target to preprocess a source file
src/engineDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/engineDevice.cpp.i
.PHONY : src/engineDevice.cpp.i

src/engineDevice.s: src/engineDevice.cpp.s
.PHONY : src/engineDevice.s

# target to generate assembly for a file
src/engineDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/engineDevice.cpp.s
.PHONY : src/engineDevice.cpp.s

src/engineModel.o: src/engineModel.cpp.o
.PHONY : src/engineModel.o

# target to build an object file
src/engineModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/engineModel.cpp.o
.PHONY : src/engineModel.cpp.o

src/engineModel.i: src/engineModel.cpp.i
.PHONY : src/engineModel.i

# target to preprocess a source file
src/engineModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/engineModel.cpp.i
.PHONY : src/engineModel.cpp.i

src/engineModel.s: src/engineModel.cpp.s
.PHONY : src/engineModel.s

# target to generate assembly for a file
src/engineModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/engineModel.cpp.s
.PHONY : src/engineModel.cpp.s

src/gameObject.o: src/gameObject.cpp.o
.PHONY : src/gameObject.o

# target to build an object file
src/gameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/gameObject.cpp.o
.PHONY : src/gameObject.cpp.o

src/gameObject.i: src/gameObject.cpp.i
.PHONY : src/gameObject.i

# target to preprocess a source file
src/gameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/gameObject.cpp.i
.PHONY : src/gameObject.cpp.i

src/gameObject.s: src/gameObject.cpp.s
.PHONY : src/gameObject.s

# target to generate assembly for a file
src/gameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/gameObject.cpp.s
.PHONY : src/gameObject.cpp.s

src/gameWindow.o: src/gameWindow.cpp.o
.PHONY : src/gameWindow.o

# target to build an object file
src/gameWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/gameWindow.cpp.o
.PHONY : src/gameWindow.cpp.o

src/gameWindow.i: src/gameWindow.cpp.i
.PHONY : src/gameWindow.i

# target to preprocess a source file
src/gameWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/gameWindow.cpp.i
.PHONY : src/gameWindow.cpp.i

src/gameWindow.s: src/gameWindow.cpp.s
.PHONY : src/gameWindow.s

# target to generate assembly for a file
src/gameWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/gameWindow.cpp.s
.PHONY : src/gameWindow.cpp.s

src/keyboardController.o: src/keyboardController.cpp.o
.PHONY : src/keyboardController.o

# target to build an object file
src/keyboardController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/keyboardController.cpp.o
.PHONY : src/keyboardController.cpp.o

src/keyboardController.i: src/keyboardController.cpp.i
.PHONY : src/keyboardController.i

# target to preprocess a source file
src/keyboardController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/keyboardController.cpp.i
.PHONY : src/keyboardController.cpp.i

src/keyboardController.s: src/keyboardController.cpp.s
.PHONY : src/keyboardController.s

# target to generate assembly for a file
src/keyboardController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/keyboardController.cpp.s
.PHONY : src/keyboardController.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pipeline.o: src/pipeline.cpp.o
.PHONY : src/pipeline.o

# target to build an object file
src/pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/pipeline.cpp.o
.PHONY : src/pipeline.cpp.o

src/pipeline.i: src/pipeline.cpp.i
.PHONY : src/pipeline.i

# target to preprocess a source file
src/pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/pipeline.cpp.i
.PHONY : src/pipeline.cpp.i

src/pipeline.s: src/pipeline.cpp.s
.PHONY : src/pipeline.s

# target to generate assembly for a file
src/pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/pipeline.cpp.s
.PHONY : src/pipeline.cpp.s

src/renderer.o: src/renderer.cpp.o
.PHONY : src/renderer.o

# target to build an object file
src/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/renderer.cpp.o
.PHONY : src/renderer.cpp.o

src/renderer.i: src/renderer.cpp.i
.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s
.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/swapChain.o: src/swapChain.cpp.o
.PHONY : src/swapChain.o

# target to build an object file
src/swapChain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/swapChain.cpp.o
.PHONY : src/swapChain.cpp.o

src/swapChain.i: src/swapChain.cpp.i
.PHONY : src/swapChain.i

# target to preprocess a source file
src/swapChain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/swapChain.cpp.i
.PHONY : src/swapChain.cpp.i

src/swapChain.s: src/swapChain.cpp.s
.PHONY : src/swapChain.s

# target to generate assembly for a file
src/swapChain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/swapChain.cpp.s
.PHONY : src/swapChain.cpp.s

src/systems/pointLightSystem.o: src/systems/pointLightSystem.cpp.o
.PHONY : src/systems/pointLightSystem.o

# target to build an object file
src/systems/pointLightSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/systems/pointLightSystem.cpp.o
.PHONY : src/systems/pointLightSystem.cpp.o

src/systems/pointLightSystem.i: src/systems/pointLightSystem.cpp.i
.PHONY : src/systems/pointLightSystem.i

# target to preprocess a source file
src/systems/pointLightSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/systems/pointLightSystem.cpp.i
.PHONY : src/systems/pointLightSystem.cpp.i

src/systems/pointLightSystem.s: src/systems/pointLightSystem.cpp.s
.PHONY : src/systems/pointLightSystem.s

# target to generate assembly for a file
src/systems/pointLightSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/systems/pointLightSystem.cpp.s
.PHONY : src/systems/pointLightSystem.cpp.s

src/systems/renderSystem.o: src/systems/renderSystem.cpp.o
.PHONY : src/systems/renderSystem.o

# target to build an object file
src/systems/renderSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/systems/renderSystem.cpp.o
.PHONY : src/systems/renderSystem.cpp.o

src/systems/renderSystem.i: src/systems/renderSystem.cpp.i
.PHONY : src/systems/renderSystem.i

# target to preprocess a source file
src/systems/renderSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/systems/renderSystem.cpp.i
.PHONY : src/systems/renderSystem.cpp.i

src/systems/renderSystem.s: src/systems/renderSystem.cpp.s
.PHONY : src/systems/renderSystem.s

# target to generate assembly for a file
src/systems/renderSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/systems/renderSystem.cpp.s
.PHONY : src/systems/renderSystem.cpp.s

src/vulkanBuffer.o: src/vulkanBuffer.cpp.o
.PHONY : src/vulkanBuffer.o

# target to build an object file
src/vulkanBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/vulkanBuffer.cpp.o
.PHONY : src/vulkanBuffer.cpp.o

src/vulkanBuffer.i: src/vulkanBuffer.cpp.i
.PHONY : src/vulkanBuffer.i

# target to preprocess a source file
src/vulkanBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/vulkanBuffer.cpp.i
.PHONY : src/vulkanBuffer.cpp.i

src/vulkanBuffer.s: src/vulkanBuffer.cpp.s
.PHONY : src/vulkanBuffer.s

# target to generate assembly for a file
src/vulkanBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkraft.dir/build.make CMakeFiles/Vulkraft.dir/src/vulkanBuffer.cpp.s
.PHONY : src/vulkanBuffer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Shaders"
	@echo "... Vulkraft"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/descriptors.o"
	@echo "... src/descriptors.i"
	@echo "... src/descriptors.s"
	@echo "... src/engineDevice.o"
	@echo "... src/engineDevice.i"
	@echo "... src/engineDevice.s"
	@echo "... src/engineModel.o"
	@echo "... src/engineModel.i"
	@echo "... src/engineModel.s"
	@echo "... src/gameObject.o"
	@echo "... src/gameObject.i"
	@echo "... src/gameObject.s"
	@echo "... src/gameWindow.o"
	@echo "... src/gameWindow.i"
	@echo "... src/gameWindow.s"
	@echo "... src/keyboardController.o"
	@echo "... src/keyboardController.i"
	@echo "... src/keyboardController.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pipeline.o"
	@echo "... src/pipeline.i"
	@echo "... src/pipeline.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/swapChain.o"
	@echo "... src/swapChain.i"
	@echo "... src/swapChain.s"
	@echo "... src/systems/pointLightSystem.o"
	@echo "... src/systems/pointLightSystem.i"
	@echo "... src/systems/pointLightSystem.s"
	@echo "... src/systems/renderSystem.o"
	@echo "... src/systems/renderSystem.i"
	@echo "... src/systems/renderSystem.s"
	@echo "... src/vulkanBuffer.o"
	@echo "... src/vulkanBuffer.i"
	@echo "... src/vulkanBuffer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

